
[var name:"randomSeed" value:0 /]

[section]

[article-title]Idyll
[/article-title]

[waypoint onEnteredView:`randomSeed=0` /]

[pullquote]
A new markup language 
for creating interactive 
documents
[/pullquote]


[waypoint onEnteredView:`randomSeed=1` /]

[pullquote]
Combine a lightweight 
markup language and reactive 
JavaScript components
[/pullquote]


[waypoint onEnteredView:`randomSeed=0` /]

[pullquote]
Visit [link href:"https://github.com/idyll-lang/idyll" text:"https://github.com/idyll-lang/idyll" /]
for more information
[/pullquote]

[waypoint onEnteredView:`randomSeed=2` /]


[pullquote]
Here is the markup for this 
page:
[/pullquote]

[waypoint onEnteredView:`randomSeed=3` /]


```
[var name:"randomSeed" value:0 /]

[section]

[article-title]Idyll
[/article-title]

[waypoint onEnteredView:`randomSeed=0` /]

[pullquote]
A new markup language 
for creating interactive 
documents
[/pullquote]


[waypoint onEnteredView:`randomSeed=1` /]

[pullquote]
Combine a light-weight 
markup language and reactive 
JavaScript components
[/pullquote]


[waypoint onEnteredView:`randomSeed=0` /]

[pullquote]
Visit [link href:"https://github.com/idyll-lang/idyll" text:"https://github.com/idyll-lang/idyll" /]
for more information
[/pullquote]

[waypoint onEnteredView:`randomSeed=2` /]


[pullquote]
Here is the markup for this 
page:
[/pullquote]

[waypoint onEnteredView:`randomSeed=3` /]

[/section]

[fixed]

[Chart type:"scatter" randomSeed:randomSeed /]

[/fixed]


```

[/section]

[fixed]

[Chart type:"scatter" randomSeed:randomSeed /]

[/fixed]
