module.exports = {
  action: require('./components/action.js'),
  analytics: require('./components/analytics.js'),
  aside: require('./components/aside.js'),
  boolean: require('./components/boolean.js'),
  button: require('./components/button.js'),
  chart: require('./components/chart.js'),
  'display-var': require('./components/display-var.js'),
  dynamic: require('./components/dynamic.js'),
  equation: require('./components/equation.js'),
  fixed: require('./components/fixed.js'),
  float: require('./components/float.js'),
  gist: require('./components/gist.js'),
  header: require('./components/header.js'),
  'idyll-logo': require('./components/idyll-logo.js'),
  inline: require('./components/inline.js'),
  link: require('./components/link.js'),
  range: require('./components/range.js'),
  slide: require('./components/slide.js'),
  slideshow: require('./components/slideshow.js'),
  svg: require('./components/svg.js'),
  table: require('./components/table.js'),
  'vega-lite': require('./components/vega-lite.js')
}
