/* parser generated by jison 0.4.17 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var parser = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,5],$V1=[1,9],$V2=[1,8],$V3=[5,8,11,14],$V4=[1,15],$V5=[1,18],$V6=[8,11,14],$V7=[16,18,19],$V8=[1,38],$V9=[1,35],$Va=[1,36],$Vb=[1,37];
var parser = {trace: function trace() { },
yy: {},
symbols_: {"error":2,"document":3,"blocks":4,"EOF":5,"block":6,"closedComponent":7,"BREAK":8,"paragraph":9,"openComponent":10,"WORDS":11,"openComponentStart":12,"openComponentEnd":13,"OPEN_BRACKET":14,"componentName":15,"CLOSE_BRACKET":16,"componentProperties":17,"FORWARD_SLASH":18,"COMPONENT_WORD":19,"PARAM_SEPARATOR":20,"componentPropertyValue":21,"null":22,"NUMBER":23,"EXPRESSION":24,"STRING":25,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",8:"BREAK",11:"WORDS",14:"OPEN_BRACKET",16:"CLOSE_BRACKET",18:"FORWARD_SLASH",19:"COMPONENT_WORD",20:"PARAM_SEPARATOR",22:"null",23:"NUMBER",24:"EXPRESSION",25:"STRING"},
productions_: [0,[3,2],[4,1],[4,2],[6,1],[6,1],[6,1],[6,1],[9,1],[9,2],[10,2],[10,3],[12,3],[12,4],[13,4],[7,4],[7,5],[15,1],[17,3],[17,4],[17,1],[21,1],[21,1],[21,1],[21,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
return $$[$0-1];
break;
case 2: case 8:
this.$ = [ $$[$0] ]
break;
case 3: case 9:
this.$ = $$[$0-1].concat([$$[$0]])
break;
case 4: case 7: case 17:
this.$ = $$[$0]
break;
case 5:
this.$ = ["br", []]
break;
case 6:
this.$ = ["p", [], $$[$0]]
break;
case 10:
this.$ = $$[$0-1].concat([[]])
break;
case 11:
this.$ = $$[$0-2].concat([$$[$0-1]])
break;
case 12:
this.$ = [$$[$0-1], []]
break;
case 13:
this.$ = [$$[$0-2], $$[$0-1]]
break;
case 14:
this.$ = ""
break;
case 15:
this.$ = [$$[$0-2], [], []]
break;
case 16:
this.$ = [$$[$0-3], $$[$0-2], []]
break;
case 18:
this.$ = [[$$[$0-2], $$[$0]]]
break;
case 19:
this.$ = $$[$0-3].concat([[$$[$0-2], $$[$0]]])
break;
case 20:
this.$ = []
break;
case 21: case 23:
this.$ = ["value", $$[$0]]
break;
case 22:
this.$ = ["expression", $$[$0]]
break;
case 24:
this.$ = ["variable", $$[$0]]
break;
}
},
table: [{3:1,4:2,6:3,7:4,8:$V0,9:6,10:7,11:$V1,12:10,14:$V2},{1:[3]},{5:[1,11],6:12,7:4,8:$V0,9:6,10:7,11:$V1,12:10,14:$V2},o($V3,[2,2]),o($V3,[2,4]),o($V3,[2,5]),o([5,8,14],[2,6],{11:[1,13]}),o($V3,[2,7]),{15:14,19:$V4},o($V3,[2,8]),{4:17,6:3,7:4,8:$V0,9:6,10:7,11:$V1,12:10,13:16,14:$V5},{1:[2,1]},o($V3,[2,3]),o($V3,[2,9]),{16:[1,21],17:20,18:[1,19],19:[1,22],22:[1,23]},o([16,18,19,22],[2,17]),o($V3,[2,10]),{6:12,7:4,8:$V0,9:6,10:7,11:$V1,12:10,13:24,14:$V5},{15:14,18:[1,25],19:$V4},{16:[1,26]},{16:[1,28],18:[1,27],19:[1,29]},o($V6,[2,12]),{20:[1,30]},o($V7,[2,20]),o($V3,[2,11]),{15:31,19:$V4},o($V3,[2,15]),{16:[1,32]},o($V6,[2,13]),{20:[1,33]},{19:$V8,21:34,23:$V9,24:$Va,25:$Vb},{16:[1,39]},o($V3,[2,16]),{19:$V8,21:40,23:$V9,24:$Va,25:$Vb},o($V7,[2,18]),o($V7,[2,21]),o($V7,[2,22]),o($V7,[2,23]),o($V7,[2,24]),o($V3,[2,14]),o($V7,[2,19])],
defaultActions: {11:[2,1]},
parseError: function parseError(str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        function _parseError (msg, hash) {
            this.message = msg;
            this.hash = hash;
        }
        _parseError.prototype = Error;

        throw new _parseError(str, hash);
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};

function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = parser;
exports.Parser = parser.Parser;
exports.parse = function () { return parser.parse.apply(parser, arguments); };
exports.main = function commonjsMain(args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}