module.exports = {
  action: require('./action.js'),
  analytics: require('./analytics.js'),
  aside: require('./aside.js'),
  boolean: require('./boolean.js'),
  button: require('./button.js'),
  chart: require('./chart.js'),
  display: require('./display.js'),
  dynamic: require('./dynamic.js'),
  equation: require('./equation.js'),
  fixed: require('./fixed.js'),
  float: require('./float.js'),
  gist: require('./gist.js'),
  header: require('./header.js'),
  inline: require('./inline.js'),
  link: require('./link.js'),
  range: require('./range.js'),
  slide: require('./slide.js'),
  slideshow: require('./slideshow.js'),
  svg: require('./svg.js'),
  table: require('./table.js')
}
