name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}
      - name: test module
        run: |
          npm i -g lerna
          lerna bootstrap
          cd packages/idyll-ast && npm test && cd ../..
          cd packages/idyll-compiler && npm test && cd ../..
          cd packages/idyll-components && npm test && cd ../..
          cd packages/idyll-cli && npm test && cd ../..
          cd packages/idyll-document && npm test && cd ../..
          cd packages/idyll-layouts && npm test && cd ../..
          cd packages/idyll-themes && npm test && cd ../..
